# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37b74e8919e819fbda10974661a0983b"
name = "GEO Rise"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://example.com/proxy/llms-txt"
subpath = "llms-txt"
prefix = "a"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,write_content,read_themes,read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
