// Public route — no Shopify auth required
import { PLAN_DEFINITIONS } from "~/services/billing.shared";

export default function TermsOfService() {
  return (
    <div
      style={{
        maxWidth: 760,
        margin: "0 auto",
        padding: "48px 24px",
        fontFamily:
          "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        color: "#202223",
        lineHeight: 1.7,
      }}
    >
      <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 4 }}>
        GEO Rise — Terms of Service
      </h1>
      <p style={{ color: "#6D7175", marginBottom: 40 }}>
        Last updated: May 17, 2026
      </p>

      <Section title="1. Acceptance of terms">
        <p>
          By installing or using GEO Rise (&quot;the App&quot;), you agree to
          these Terms of Service (&quot;Terms&quot;) on behalf of yourself and
          the business you represent. If you do not agree, do not install or use
          the App. These Terms form a binding agreement between you and Boda
          Apps (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
        </p>
      </Section>

      <Section title="2. Description of service">
        <p>
          GEO Rise is a Shopify app that helps merchants improve their
          discoverability in AI-powered search engines. Features include
          llms.txt generation, AI readiness auditing, JSON-LD schema injection,
          AI agent simulation, and visibility tracking. Features vary by
          subscription plan.
        </p>
      </Section>

      <Section title="3. Subscription and billing">
        <ul>
          <li>
            GEO Rise is available on a Free plan and paid plans (
            {PLAN_DEFINITIONS.GROWTH.name} at $
            {PLAN_DEFINITIONS.GROWTH.price}/month,{" "}
            {PLAN_DEFINITIONS.PRO.name} at ${PLAN_DEFINITIONS.PRO.price}/month,{" "}
            {PLAN_DEFINITIONS.ENTERPRISE.name} at $
            {PLAN_DEFINITIONS.ENTERPRISE.price}/month).
          </li>
          <li>
            Paid plans are billed monthly through Shopify&apos;s standard app
            billing system. Charges appear on your Shopify invoice.
          </li>
          <li>
            Paid plans include a 7-day free trial. You will not be charged until
            the trial period ends. Cancel anytime before the trial ends to avoid
            charges.
          </li>
          <li>
            Subscriptions auto-renew each billing cycle unless cancelled.
          </li>
          <li>
            Downgrading or cancelling takes effect at the end of the current
            billing period. No partial refunds are issued.
          </li>
        </ul>
      </Section>

      <Section title="4. Acceptable use">
        <p>You agree not to:</p>
        <ul>
          <li>
            Use the App in any way that violates Shopify&apos;s Partner Program
            Agreement or Acceptable Use Policy.
          </li>
          <li>
            Attempt to reverse engineer, decompile, or extract source code from
            the App.
          </li>
          <li>
            Use the App to generate content that is misleading, inaccurate, or
            deceptive to AI systems or end consumers.
          </li>
          <li>
            Exceed usage limits of your plan tier through automated means or
            API abuse.
          </li>
        </ul>
      </Section>

      <Section title="5. Data and privacy">
        <p>
          Your use of the App is governed by our{" "}
          <a href="/privacy">Privacy Policy</a>, which is incorporated into
          these Terms. By using the App you consent to our collection and use of
          data as described therein.
        </p>
      </Section>

      <Section title="6. Intellectual property">
        <p>
          GEO Rise and all related trademarks, software, and content are owned
          by Boda Apps. You are granted a limited, non-exclusive,
          non-transferable licence to use the App solely for your Shopify store
          operations during your subscription period.
        </p>
        <p>
          Content generated by the App (llms.txt files, audit reports, schema
          markup) is yours to use freely for your store.
        </p>
      </Section>

      <Section title="7. Disclaimer of warranties">
        <p>
          The App is provided &quot;as is&quot; without warranties of any kind.
          We do not guarantee that using GEO Rise will result in increased
          traffic, revenue, or AI citations. AI search engine behaviour is
          outside our control and changes frequently.
        </p>
        <p>
          We do not guarantee 100% uptime. Planned and unplanned maintenance
          may occur.
        </p>
      </Section>

      <Section title="8. Limitation of liability">
        <p>
          To the maximum extent permitted by law, Boda Apps shall not be liable
          for any indirect, incidental, special, or consequential damages arising
          from your use of the App, including loss of revenue, loss of data, or
          business interruption. Our total liability to you for any claim shall
          not exceed the amount you paid us in the three months preceding the
          claim.
        </p>
      </Section>

      <Section title="9. Termination">
        <p>
          You may stop using the App at any time by uninstalling it from your
          Shopify store. We reserve the right to suspend or terminate your access
          if you violate these Terms, with or without notice.
        </p>
      </Section>

      <Section title="10. Governing law">
        <p>
          These Terms are governed by the laws of Norway. Any disputes shall be
          resolved in the courts of Oslo, Norway, unless otherwise required by
          applicable consumer protection law.
        </p>
      </Section>

      <Section title="11. Changes to terms">
        <p>
          We may update these Terms at any time. We will notify you of material
          changes via the App. Continued use after changes constitutes
          acceptance.
        </p>
      </Section>

      <Section title="12. Contact">
        <p>
          Boda Apps
          <br />
          Email: <a href="mailto:hello@boda.no">hello@boda.no</a>
          <br />
          Norway
        </p>
      </Section>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2
        style={{
          fontSize: 18,
          fontWeight: 600,
          marginBottom: 12,
          borderBottom: "1px solid #E4E5E7",
          paddingBottom: 8,
        }}
      >
        {title}
      </h2>
      {children}
    </section>
  );
}
